# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10
  
  
[[main_right]]
  #name = "TIL"
  name = "Technical Documents"
  url = "displayDocs"
  weight = 20
  
  
#[[main_right]]
#  name = "Today I Learned"
#  url = "tutorial/"
#  weight = 30

[[main_right]]
  name = "Posts"
  url = "#posts"
  weight = 40

[[main_right]]
  name = "Projects"
  url = "#projects"
  weight = 50


#[[main_right]]
# name = "Contact"
# url = "#contact"
# weight = 60



#[[main]]
#  name = "Publications"
#  url = "featured/"
#  weight = 40


#[[main]]
#  name = "talks"
#  url = "#talks"
#  weight = 70





# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#   name = "CV"
#  url = "files/cv.pdf"
# weight = 70
